### ISSUE TITLE
assets are missing: "Error  level.lua:50: Could not open file assets/brick1.png. Does not exist..."

### ISSUE THREAD

**Issue by MrKangar** [Grinshpon/Volk3D#2]
if someone in the future faces the same problem just create an "assets" folder inside "src" and put 3 PNGs "brick1", "brick2", and "barrel". don't forget to open the src folder with love2D not the VOLK3D-master folder.
good luck.

**Comment by Grinshpon** [comment]
I didn't include the textures in the repo, partly because I didn't expect anyone would actually use them. So the textures should all be 64x64 png's.
